### ISSUE TITLE
Timeout for requests

### ISSUE THREAD

**Issue by mackonen** [milvus-io/milvus-sdk-node#103]
**Describe the feature:**
PyMilvus has a nice timeout setting for requests. Could we have the same for node?

**Describe a specific use case for the feature:**
I don't want my whole service to hang indefinitely if the milvus server doesn't respond for some reason.

**Comment by shanghaikid** [comment]
> **Describe the feature:** PyMilvus has a nice timeout setting for requests. Could we have the same for node?
> 
> **Describe a specific use case for the feature:** I don't want my whole service to hang indefinitely if the milvus server doesn't respond for some reason.

Definitely , we need a timeout for this.  We will add timeout soon. Thanks.
