### ISSUE TITLE
How to specify grpc ChannelOptions

### ISSUE THREAD

**Issue by logidelic** [milvus-io/milvus-sdk-node#137]
Hello!

While using `milvus-sdk-node`, I'm frequently running into the grpc issue mentioned [here](https://github.com/grpc/grpc-node/issues/1907).

It looks like there's a workaround to the problem by overriding the default grpc `channelOptions`.  Are these somehow exposed by the Milvus SDK?

Thank you!

**Comment by shanghaikid** [comment]
> Hello!
> 
> While using `milvus-sdk-node`, I'm frequently running into the grpc issue mentioned [here](https://github.com/grpc/grpc-node/issues/1907).
> 
> It looks like there's a workaround to the problem by overriding the default grpc `channelOptions`. Are these somehow exposed by the Milvus SDK?
> 
> Thank you!

We haven't exposed this in the release. 

Here is the code, https://github.com/milvus-io/milvus-sdk-node/blob/64a941bc2aeaa299104d6db810f5f006b651e2c0/milvus/BaseClient.ts#L66

And also I think the params of the client constructor should be an object other than 4 parameters.  We will do it in the next release.

If you would like to contribute to this, that will be great.
