### ISSUE TITLE
search results are wrong

### ISSUE THREAD

**Issue by lutiayi** [milvus-io/milvus-sdk-node#184]
**Describe the bug:**
search results are wrong
**Steps to reproduce:**

search results are wrong

const { MilvusClient, DataType } = require('@zilliz/milvus2-sdk-node')
const collectionName = 'search_test'
const vectors = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]

const params = {
    collection_name: collectionName,
    description: 'search test',
    fields: [
        {
            name: 'id',
            data_type: DataType.Int64,
            is_primary_key: true,
            description: ''
        },
        {
            name: 'content',
            data_type: DataType.VarChar,
            max_length: 4096,
            description: ''
        }, {
            name: 'vector',
            description: '',
            data_type: DataType.FloatVector,
            dim: 2
        }
    ]
}

async function testSearch() {
    const config = $configure.getConfig()
    const ssl = false

    const milvusClient = new MilvusClient(
        config.milvus.host,
        ssl,
        config.milvus.user,
        config.milvus.pwd
    )
    const hasCollection = await milvusClient.hasCollection({ collection_name: collectionName })
    if (hasCollection.value) {
        //await milvusClient.dropCollection({ collection_name: collectionName })
    } else {
        const resStatus = await milvusClient.createCollection(params)
        console.log(resStatus.error_code)
        console.log(resStatus.reason)

        await createIndex(milvusClient)

        const data = []
        for (var i = 0; i < vectors.length; i++) {
            data.push({
                'id': i,
                'content': i,
                'vector': vectors[i]
            })
        }
        const insertStatus = await milvusClient.insert({
            collection_name: collectionName,
            fields_data: data,
        })
        console.log(insertStatus)
        await milvusClient.flush({ collection_names: [collectionName] })
    }

    const loadStatus = await milvusClient.loadCollection({
        collection_name: collectionName
    })

    console.log(loadStatus)

    const searchParams = {
        anns_field: 'vector',
        topk: 1,
        metric_type: 'L2',
        params: JSON.stringify({ nprobe: 1 })
    }

    const tableHeadersResults = await milvusClient.search({
        collection_name: collectionName,
        vectors: [[1, 2], [3, 4], [5, 6], [1, 2]],
        search_params: searchParams,
        vector_type: DataType.FloatVector
    })

    //  [5, 6], [1, 2] get wrong results

    milvusClient.closeConnection()
    return true
}

async function createIndex(milvusClient) {
    const index_params = {
        metric_type: 'L2',
        index_type: 'IVF_FLAT',
        params: JSON.stringify({ nlist: 1 })
    }

    await milvusClient.createIndex({
        collection_name: collectionName,
        field_name: 'vector',
        extra_params: index_params,
    })
}

**Milvus-node-sdk version:**
2.2.12
**Milvus version:**
latest

**Comment by shanghaikid** [comment]
ok, let me double check this.

**Comment by shanghaikid** [comment]
you are correct on this pr. https://github.com/milvus-io/milvus-sdk-node/pull/173. 
I did not understand your pr. 
Thanks.
