### ISSUE TITLE
Error: Insert fail: some field does not exist for this collection in line. 0

### ISSUE THREAD

**Issue by DeeWooo** [milvus-io/milvus-sdk-node#186]
**Describe the bug:**
我在用langchainjs集成milvus，希望构建知识库检索的功能，遇到这个问题：
Error: Insert fail: some field does not exist for this collection in line. 0

**Steps to reproduce:**

1.使用https://github.com/zilliztech/cloud-vectordb-examples/blob/master/node/HelloZillizCloud.js创建好了collection，
2.使用langchainjs官网集成milvus的例子https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/milvus，Index and query docs标签下
`import { Milvus } from "langchain/vectorstores/milvus";
import { OpenAIEmbeddings } from "langchain/embeddings/openai";

// text sample from Godel, Escher, Bach
const vectorStore = await Milvus.fromTexts(
  [
    "Tortoise: Labyrinth? Labyrinth? Could it Are we in the notorious Little\
            Harmonic Labyrinth of the dreaded Majotaur?",
    "Achilles: Yiikes! What is that?",
    "Tortoise: They say-although I person never believed it myself-that an I\
            Majotaur has created a tiny labyrinth sits in a pit in the middle of\
            it, waiting innocent victims to get lost in its fears complexity.\
            Then, when they wander and dazed into the center, he laughs and\
            laughs at them-so hard, that he laughs them to death!",
    "Achilles: Oh, no!",
    "Tortoise: But it's only a myth. Courage, Achilles.",
  ],
  [{ id: 2 }, { id: 1 }, { id: 3 }, { id: 4 }, { id: 5 }],
  new OpenAIEmbeddings(),
  {
    collectionName: "goldel_escher_bach",
  }
);

// or alternatively from docs
const vectorStore = await Milvus.fromDocuments(docs, new OpenAIEmbeddings(), {
  collectionName: "goldel_escher_bach",
});

const response = await vectorStore.similaritySearch("scared", 2);
`
3.我将ids改成
`[
    { id: 2, word_count: 24, book_intro: Math.floor(Math.random() * 1000) },
    { id: 1, word_count: 4, book_intro: Math.floor(Math.random() * 1000) },
    { id: 3, word_count: 6, book_intro: Math.floor(Math.random() * 1000) },
    { id: 4, word_count: 2, book_intro: Math.floor(Math.random() * 1000) },
    { id: 5, word_count: 9, book_intro: Math.floor(Math.random() * 1000) },
]`
4. 跑起来报上面的错，请帮忙看看怎么回事，谢谢

**Milvus-node-sdk version:**
2.2.10
**Milvus version:**
zilliz cloud

**Comment by shanghaikid** [comment]
ok, let me check this later today.

**Comment by shanghaikid** [comment]
I will add an example in the repo's doc for those who like to use langchain.js tomorrow.

**Comment by DeeWooo** [comment]
> I will add an example in the repo's doc for those who like to use langchain.js tomorrow.

hi, where is the example?

**Comment by shanghaikid** [comment]
> > I will add an example in the repo's doc for those who like to use langchain.js tomorrow.
> 
> hi, where is the example?

https://github.com/milvus-io/milvus-sdk-node/tree/main/example/LangChain

**Comment by DeeWooo** [comment]
> > > I will add an example in the repo's doc for those who like to use langchain.js tomorrow.
> > 
> > 
> > hi, where is the example?
> 
> https://github.com/milvus-io/milvus-sdk-node/tree/main/example/LangChain

thank you！

**Comment by DeeWooo** [comment]
> > > I will add an example in the repo's doc for those who like to use langchain.js tomorrow.
> > 
> > 
> > hi, where is the example?
> 
> https://github.com/milvus-io/milvus-sdk-node/tree/main/example/LangChain

I used the example above and got the following error. I am using Zilliz Cloud.

Error: ErrorCode: UnexpectedError. Reason: index doesn't exist, collectionID 441713954587545704

**Comment by DeeWooo** [comment]
I found that there were no successfully built indexes on the Zilliz console, and after manually creating them, the problem was solved. ‘Metric Type’ needs to be manually selected. I chose ‘L2’.
Why is that?
![image](https://github.com/milvus-io/milvus-sdk-node/assets/7700516/9d2a46da-b877-410c-a5ec-5b3162ec8445)

**Comment by shanghaikid** [comment]
> I found that there were no successfully built indexes on the Zilliz console, and after manually creating them, the problem was solved. ‘Metric Type’ needs to be manually selected. I chose ‘L2’. Why is that? ![image](https://user-images.githubusercontent.com/7700516/244007734-9d2a46da-b877-410c-a5ec-5b3162ec8445.png)

Maybe you can try a new collection to see if it is working.  not the old name 'books'.

**Comment by DeeWooo** [comment]
> > I found that there were no successfully built indexes on the Zilliz console, and after manually creating them, the problem was solved. ‘Metric Type’ needs to be manually selected. I chose ‘L2’. Why is that? ![image](https://user-images.githubusercontent.com/7700516/244007734-9d2a46da-b877-410c-a5ec-5b3162ec8445.png)
> 
> Maybe you can try a new collection to see if it is working. not the old name 'books'.
yes,this is a new collection. you can try to use zilliz cloud
![image](https://github.com/milvus-io/milvus-sdk-node/assets/7700516/d6e43e81-e9cb-4017-8003-8b4739dee574)

**Comment by DeeWooo** [comment]
> > > > I found that there were no successfully built indexes on the Zilliz console, and after manually creating them, the problem was solved. ‘Metric Type’ needs to be manually selected. I chose ‘L2’. Why is that? ![image](https://user-images.githubusercontent.com/7700516/244007734-9d2a46da-b877-410c-a5ec-5b3162ec8445.png)
> > > 
> > > 
> > > Maybe you can try a new collection to see if it is working. not the old name 'books'.
> > > yes,this is a new collection. you can try to use zilliz cloud
> > > ![image](https://user-images.githubusercontent.com/7700516/244010833-d6e43e81-e9cb-4017-8003-8b4739dee574.png)
> 
> I tested it's working. it's weird. ![image](https://user-images.githubusercontent.com/185051/244014076-a3c16df1-c11f-4c69-9049-70e151e4703e.png) ![image](https://user-images.githubusercontent.com/185051/244014411-1643d85a-f235-4bb4-8045-e3189bc18f64.png)

why?
there are my parameter
export const address =
    'https://in01-c664772af99277c.aws-us-west-2.vectordb.zillizcloud.com:19532';
export const username = 'ttc'; // optional username
export const password = 'Ttc.zilliz'; // optional password
export const ssl = true; // secure or not

**Comment by shanghaikid** [comment]
> why?
> there are my parameter
> export const address =
> 'https://in01-c664772af99277c.aws-us-west-2.vectordb.zillizcloud.com:19532';
> export const username = 'ttc'; // optional username
> export const password = 'Ttc.zilliz'; // optional password
> export const ssl = true; // secure or not

I know. I just reviewed the langchain code, zilliz cloud doesn't support the index type used in langchain.

I will contribute a zilliz vector store in langchain.js. 

Anyway,  langchain is just a chain tool,  you archive your target without it and in a more controllable  way. 
1. get embedding from openAI's api
2. insert embedding into milvus
3. search with milvus

**Comment by DeeWooo** [comment]
> > why? 为什么？
> > there are my parameter有我的参数
> > export const address =导出常量地址 =
> > 'https://in01-c664772af99277c.aws-us-west-2.vectordb.zillizcloud.com:19532';“https://in01-c664772af99277c.aws-us-west-2.vectordb.zillizcloud.com:19532”;
> > export const username = 'ttc'; // optional username导出常量用户名 = 'TTC';可选用户名
> > export const password = 'Ttc.zilliz'; // optional password导出常量密码 = 'Ttc.zilliz';可选密码
> > export const ssl = true; // secure or not导出常量 SSL = 真;安全与否
> 
> I know. I just reviewed the langchain code, zilliz cloud doesn't support the index type used in langchain.我知道。我刚刚查看了语言链代码，zilliz 云不支持语言链中使用的索引类型。
> 
> I will contribute a zilliz vector store in langchain.js.我将在 langchain.js 中贡献一个 zilliz 向量存储。
> 
> Anyway, langchain is just a chain tool, you can archive your target without it and in a more controllable way.无论如何，langchain 只是一个链工具，您可以在没有它的情况下以更可控的方式存档目标。
> 
> 1. get embedding from openAI's api从OpenAI的API获取嵌入
> 2. insert embedding into milvus将嵌入插入 milvus
> 3. search with milvus 使用米尔维斯搜索

ok
i understand
