### ISSUE TITLE
useDatabase is not available

### ISSUE THREAD

**Issue by geminigeek** [milvus-io/milvus-sdk-node#197]
it seems useDatabase is not available in node api the docs mentions it . but its not there getting error
```
TypeError: client.useDatabase is not a function
```

**Milvus-node-sdk version:**
2.2.18
**Milvus version:**
2.2.10

**Comment by shanghaikid** [comment]
I think the doc is wrong. I will fix it. 

Here is the correct code.

```
 await milvusClient.use({  db_name: 'db name' });
```
Here is an working example
https://github.com/milvus-io/milvus-sdk-node/blob/main/test/Database.spec.ts
