### ISSUE TITLE
Provide a count function

### ISSUE THREAD

**Issue by geminigeek** [milvus-io/milvus-sdk-node#208]
Provide a count function that sends only count of the items found of a query result, currently query sends ids, i don't want ids i just want a count

**Describe a specific use case for the feature:**
1. it might help in many cases where a queue/process is feeding the data into a collection, to track count of items present 
2. it will be good for analytics of a specific meta data field 
3. items added in last n minutes / hours

**Comment by shanghaikid** [comment]
if you want count, you can just count it by yourself, here is my test code, all you need is the `res.data.length`? 

```
  it(`Query with data limit only`, async () => {
    const expr = 'age > 0';
    const res = await milvusClient.query({
      collection_name: COLLECTION_NAME,
      expr: expr,
      output_fields: ['age', 'meta', VECTOR_FIELD_NAME],
      limit: 3,
    });

    expect(res.data.length).toBe(3);
  });
```

**Comment by geminigeek** [comment]
this is perfect but only if the query is running on the server where milvus is installed, if i run it from another server all ids are transferring over the network, while i just want a count!

**Comment by shanghaikid** [comment]
> this is perfect but only if the query is running on the server where milvus is installed, if i run it from another server all ids are transferring over the network, while i just want a count!

As far as I know, milvus doesn't provide these feature, we can do nothing more in the client(sdk), I can provide the `length` for you directly, but the load will still be transferred through the network.  

if you don't want too much load, you can set the out_fields with only 1 field. 

Maybe you can create an issue in the milvus repo.

**Comment by geminigeek** [comment]
hi, 
thanks for your reply, i was thinking same i will open an issue in milvus repo.
