### ISSUE TITLE
Can not work on `grpc/grpc-js: 1.8.19` default dependency

### ISSUE THREAD

**Issue by yuyicai** [milvus-io/milvus-sdk-node#209]
**Describe the bug:**
`@zilliz/milvus2-sdk-node` can not work on `grpc/grpc-js: 1.8.19` default dependency

**Steps to reproduce:**

error demo: https://github.com/yuyicai/milvus2-sdk-node_grpc-error-demo

- milvus2-sdk-node version:

```json
  "dependencies": {
    "@zilliz/milvus2-sdk-node": "=2.2.20"
  }
```

- node version:

```
v18.16.1
```

- install dependencies:
  run `npm install`, the `grcp/grpc-js: 1.8.19` dependency will be installed automatically.

```json

    "node_modules/@grpc/grpc-js": {
      "version": "1.8.19",
      "resolved": "https://registry.npmjs.org/@grpc/grpc-js/-/grpc-js-1.8.19.tgz",
      "integrity": "sha512-yCkvhtstJvUL3DEQAF5Uq5KoqQL27MTdfxVYvGsGduoGxiJcRCvJ29t5OmLfLhRuRpjAQ1OlhJD/IPOfX+8jNw==",
      "dependencies": {
        "@grpc/proto-loader": "^0.7.0",
        "@types/node": ">=12.12.47"
      },
      "engines": {
        "node": "^8.13.0 || >=10.10.0"
      }
    },

```

- error:
  `index.ts`

```ts
import { MilvusClient } from '@zilliz/milvus2-sdk-node';

(async () => {
  // build client
  const milvusClient = new MilvusClient({
    address: 'localhost:19530',
  });
  await milvusClient.checkHealth();
})();
```

run `ts-node index.ts`, the error is:

```
/milvus-foo/node_modules/@grpc/grpc-js/src/transport.ts:255
    logging.trace(LogVerbosity.DEBUG, 'keepalive', '(' + this.channelzRef.id + ') ' + this.subchannelAddressString + ' ' + text);
                                                                          ^
TypeError: Cannot read properties of undefined (reading 'id')
    at Http2Transport.keepaliveTrace (/milvus-foo/node_modules/@grpc/grpc-js/src/transport.ts:255:75)
    at Http2Transport.maybeStartKeepalivePingTimer (/milvus-foo/node_modules/@grpc/grpc-js/src/transport.ts:367:12)
    at new Http2Transport (/milvus-foo/node_modules/@grpc/grpc-js/src/transport.ts:151:12)
    at ClientHttp2Session.<anonymous> (/milvus-foo/node_modules/@grpc/grpc-js/src/transport.ts:622:17)
    at Object.onceWrapper (node:events:628:26)
    at ClientHttp2Session.emit (node:events:513:28)
    at ClientHttp2Session.emit (node:domain:489:12)
    at emit (node:internal/http2/core:330:3)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

- it work on `grpc/grpc-js: 1.8.17` dependency
  when change the `grpc/grpc-js` dependency to `1.8.17`, it works.
```json
  "dependencies": {
    "@zilliz/milvus2-sdk-node": "=2.2.20",
    "@grpc/grpc-js": "=1.8.17"
  }
```

**Milvus-node-sdk version:**
`2.2.20`
**Milvus version:**
docker image `milvusdb/milvus:v2.2.11`

**Comment by shanghaikid** [comment]
Why do you have grpc v1.8.19 installed? 

In yarn.lock, we only have v1.8.17
![image](https://github.com/milvus-io/milvus-sdk-node/assets/185051/af683596-791c-4303-84ec-afc6b314624c)

**Comment by yuyicai** [comment]
> Why do you have grpc v1.8.19 installed?
> 
> In yarn.lock, we only have v1.8.17 ![image](https://user-images.githubusercontent.com/185051/255854136-af683596-791c-4303-84ec-afc6b314624c.png)

I use `@zilliz/milvus2-sdk-node` on my project, the `@grpc/grpc-js: 1.8.19` dependency will be installed defaultly

**Comment by yuyicai** [comment]
error-demo: https://github.com/yuyicai/milvus2-sdk-node_grpc-error-demo
