### ISSUE TITLE
Fail to run langchain  milvus vector store sample

### ISSUE THREAD

**Issue by webup** [milvus-io/milvus-sdk-node#217]
**Describe the bug:**

Fail to run this [sample](https://js.langchain.com/docs/modules/data_connection/vectorstores/integrations/milvus#index-and-query-docs) with error messages: `E Connection to dns:in03-02861d92d812d64.api.gcp-us-west1.zillizcloud.com at 34.160.220.160:443 rejected by server because of excess pings`. 

**Steps to reproduce:**

![image](https://github.com/milvus-io/milvus-sdk-node/assets/2936504/c4005369-ed4f-4b1a-a714-f9bf4c26a10d)

**Milvus-node-sdk version:** 2.2.23

**Milvus version:** Ziliz Cloud Serverless (Free)

**Comment by webup** [comment]
> looks like there is an issue on the server, we will investigate it.

any updates? :)

**Comment by shanghaikid** [comment]
> > looks like there is an issue on the server, we will investigate it.
> 
> any updates? :)

Would you try the dedicated server? serverless may have some problem on langchain.js.  it needs to be update.

**Comment by webup** [comment]
> > > looks like there is an issue on the server, we will investigate it.
> > 
> > 
> > any updates? :)
> 
> Would you try the dedicated server? serverless may have some problem on langchain.js. it needs to be update.

Got you, dedicated server works. Looking forward to the serverless update. 💪

**Comment by webup** [comment]
Hi there, any updates or further guides on the server side?

I've noticed and tried latest milvus client [update](https://github.com/hwchase17/langchainjs/pull/2345) on langchain-js, still not working w/ serverless server. :(

**Comment by shanghaikid** [comment]
@nameczz could you please give an example?

**Comment by nameczz** [comment]
@webup Hi, we update example now. Please have a check.

**Comment by webup** [comment]
> @webup Hi, we update example now. Please have a check.

Your example in this repo uses username and password, while serverless takes token, so I followed [this ut](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/vectorstores/tests/milvus.int.test.ts#L43) as sample, and still failed to connect the server.

**Comment by nameczz** [comment]
@webup hi, I'm working well after replace the real token, address and openaikey.
But i'm face this error once, resolved it after open my vpn :)
![ec87cb9d-8361-4675-be0e-92c069b7924b](https://github.com/milvus-io/milvus-sdk-node/assets/20559208/cd3019c9-0fbf-4ef0-85b7-d10e78c96845)
