### ISSUE TITLE
search api only return `score` and `id`

### ISSUE THREAD

**Issue by disflyer** [milvus-io/milvus-sdk-node#222]
**Describe the bug:**
/milvus/grpc/Data.ts
```javascript
const output_fields = [
        'id',
        ...(promise.results.output_fields ||
          fields_data.map(f => f.field_name)),
      ];
```
`promise.results.output_fields` is empty while `data.output_fields` is not.  I changed `promise.results.output_fields` to `data.output_fields` and it works.
**Steps to reproduce:**

1.call search api
```javascript
this.milvus.search({
    collection_name: 'LangChainCollection_001',
    output_fields: ['source', 'text'],
    search_params: {
        params: '{"ef":250}',
        anns_field: 'vector',
        topk: '10',
        metric_type: 'L2',
        round_decimal: -1
    },
    vector_type: 101,
    vectors: [
        [...]
    ]
})
```
2. Not return these `output_fields` in request
<img width="626" alt="Screen Shot 2023-08-08 at 15 06 03" src="https://github.com/milvus-io/milvus-sdk-node/assets/22723892/8ba96d08-abd3-412f-b35c-fde6fa580cc8">

3.change `promise.results.output_fields` to `data.output_fields`, it works.

**Milvus-node-sdk version:**
@zilliz/milvus2-sdk-node: "^2.2.23"
**Milvus version:**
v2.2.6

**Comment by shanghaikid** [comment]
I didn't expect that milvus v2.2.6 does't give the output_fields.  Maybe we need a compatible layer here.

**Comment by shanghaikid** [comment]
Can you try newer milvus?

**Comment by disflyer** [comment]
> Can you try newer milvus?

Which version should I use?

**Comment by shanghaikid** [comment]
> > Can you try newer milvus?
> 
> Which version should I use?

I guess >= 2.2.10

**Comment by disflyer** [comment]
> I didn't expect that milvus v2.2.6 does't give the output_fields. Maybe we need a compatible layer here.

it gives, but looks like `output_fields ` is empty Array. So `||` is not work for it in `...(promise.results.output_fields ||
          fields_data.map(f => f.field_name)),`.

**Comment by shanghaikid** [comment]
Would you like to make a pr here? 👍

**Comment by disflyer** [comment]
> Would you like to make a pr here? 👍
Glad to do.
