### ISSUE TITLE
MilvusClient instantiation is not catchable

### ISSUE THREAD

**Issue by mohhsen67** [milvus-io/milvus-sdk-node#255]
**Describe the bug:**
I am using `"@zilliz/milvus2-sdk-node": "^2.3.2"` in a NestJS app. The problem is that when `milvus-standalone` is not running, instantiation of `MilvusClient` throws an error and the error is not catchable using try-catch block.

The following is my code:

```
try {
      this.client = new MilvusClient('localhost:19530');
} catch (error) {
      console.error('Failed to connect to Milvus:', error);
}
```

**Steps to reproduce:**

1. Stop milvus-standalone docker container.
2. Instantiate MilvusClient.

**Milvus-node-sdk version:**
`^2.3.2`

**Milvus version:**
`milvusdb/milvus:v2.2.9`

**Comment by shanghaikid** [comment]
it's not a good practice to throw errors in asynchronous operations.  You can make use of the `connectPromise`, it is catchable. 

```
  it(`should catch error for invalid address`, async() => {
    const milvusClient = new MilvusClient(`invalid-address`);
    milvusClient.connectPromise.catch((e)=>{
      console.log('connect failed')
    })
  });

```
