### ISSUE TITLE
The dynamicSchema in the example is OK?

### ISSUE THREAD

**Issue by dongwangdw** [milvus-io/milvus-sdk-node#256]
I did not find any fields related to dynamic schema in the coresponding example file. 
Is it really a dynamicSchema example?
In the python example, at least an option: ` enable_dynamic_field=True`. 
But in the ts file, no such thing at all.

**Comment by shanghaikid** [comment]
if you don't specified your schema, `enable_dynamic_field` is always on, for example
```javascript
const client = new MilvusClient(ip)
const create = await client.createCollection({
    collection_name: COLLECTION_NAME,
    dimension: 8,
  });
```
if you specified your schema, you can must set the `enable_dynamic_field` in the params. 

```javascript
const client = new MilvusClient(ip)
const create = await client.createCollection({
    collection_name: COLLECTION_NAME,
    fields: [...],
    enable_dynamic_field: true
  });
```

**Comment by dongwangdw** [comment]
> if you don't specified your schema, `enable_dynamic_field` is always on, for example
> 
> ```js
> const client = new MilvusClient(ip)
> const create = await client.createCollection({
>     collection_name: COLLECTION_NAME,
>     dimension: 8,
>   });
> ```
> 
> if you specified your schema, you can must set the `enable_dynamic_field` in the params.
> 
> ```js
> const client = new MilvusClient(ip)
> const create = await client.createCollection({
>     collection_name: COLLECTION_NAME,
>     fields: [...],
>     enable_dynamic_field: true
>   });
> ```

OK, Thanks for the explannation.
