### ISSUE TITLE
Add sparse float vector support

### ISSUE THREAD

**Issue by zhengbuqian** [milvus-io/milvus-sdk-node#290]
Milvus 2.4 has added beta support to sparse float vector to allow efficient storing, indexing and searching of such vectors. The main targeted use case is to support learned sparse models such as SPLADE and statistics based methods such as BM25. 

We need to add sparse float vector to node SDK as well. See: https://github.com/milvus-io/milvus/issues/29419#issuecomment-2024887328 for more details.

Thanks a lot for the efforts!

**Comment by shanghaikid** [comment]
it is in the 2.4 branch,  thanks.

**Comment by shanghaikid** [comment]
it will be released once milvus 2.4 released.

**Comment by zhengbuqian** [comment]
thanks @shanghaikid! that is great to know!

We are actively making more advanced features available to sparse fields such as range search and grouping search etc. I hope those features will just work once we finished on the milvus side, but let's leave this issue open and verify when those are ready.

We are planning to have those advanced feature support added in the next major release though, not in 2.4.
