### ISSUE TITLE
Which should I trust? autoID or auto_id?

### ISSUE THREAD

**Issue by hellohejinyu** [milvus-io/milvus-sdk-node#333]
**Describe the bug:**

<img width="1155" alt="image" src="https://github.com/milvus-io/milvus-sdk-node/assets/8766034/81e77dff-6604-44d7-a44d-a657f039a187">

The field in the official documentation is auto_id, and it seems that auto_id has the same unified format as other fields.

![image](https://github.com/milvus-io/milvus-sdk-node/assets/8766034/fc208041-e711-48a2-93d9-ce6e594a6af2)

But when I was using it, I found that autoID was used in the sdk type declaration file. So I was confused, I should follow the usage in the type declaration file, right?

**Milvus-node-sdk version:** 2.4.3

**Comment by shanghaikid** [comment]
Please use autoID in the schema instead of auto_id. You can also set autoID in the request body, but setting it in the schema is more future-proof.

The doc is incorrect, I will fix the doc, thanks.
