### ISSUE TITLE
DEADLINE_EXCEEDED: Deadline exceeded

### ISSUE THREAD

**Issue by 759325100** [milvus-io/milvus-sdk-node#337]
**Describe the bug:**
frequently execute insert, throw error:
 {
      "code": 4,
      "message": "4 DEADLINE_EXCEEDED: Deadline exceeded",
      "stack": "Error: 4 DEADLINE_EXCEEDED: Deadline exceeded\n    at callErrorFromStatus (/Users/yinmeng/Documents/waroom/work/qcc/face-search-api/node_modules/@zilliz/milvus2-sdk-node/node_modules/@grpc/grpc-js/src/call.ts:81:17)\n    at Object.onReceiveStatus (/Users/yinmeng/Documents/waroom/work/qcc/face-search-api/node_modules/@zilliz/milvus2-sdk-node/node_modules/@grpc/grpc-js/src/client.ts:356:55)\n    at /Users/yinmeng/Documents/waroom/work/qcc/face-search-api/node_modules/@zilliz/milvus2-sdk-node/node_modules/@grpc/grpc-js/src/call-interface.ts:149:27\n    at Object.onReceiveStatus (/Users/yinmeng/Documents/waroom/work/qcc/face-search-api/node_modules/@zilliz/milvus2-sdk-node/milvus/utils/Grpc.ts:184:23)\n    at Object.onReceiveStatus (/Users/yinmeng/Documents/waroom/work/qcc/face-search-api/node_modules/@zilliz/milvus2-sdk-node/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)\n    at Object.onReceiveStatus (/Users/yinmeng/Documents/waroom/work/qcc/face-search-api/node_modules/@zilliz/milvus2-sdk-node/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)\n    at /Users/yinmeng/Documents/waroom/work/qcc/face-search-api/node_modules/@zilliz/milvus2-sdk-node/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)\nfor call at\n",
      "name": "Error"
    }

**Steps to reproduce:**
init
```typescript
import { MilvusClient } from '@zilliz/milvus2-sdk-node'
const milvusClient = new MilvusClient( {address: 'xxx:19530', database: 'xxxx', timeout: 3000 })
```
1. create collect and loaded
```typescript
await milvusClient.createCollection({
      collection_name:'xxxx',
      description: 'xxxxx',
      consistency_level: 'Bounded',
      fields: [
        { name: 'id', data_type: DataType.VarChar, is_primary_key: true, max_length: 32, description: '主键' },
        { name: 'vector', data_type: DataType.FloatVector, dim: 512, description: '向量' }
      ]
    })
await milvusClient.createIndex({
      collection_name:'xxxx',
      field_name: 'vector',
      index_name: 'idx_flat_vector',
      metric_type: 'COSINE',
      index_type: IndexType.FLAT,
      params: {
      }
    })
await milvusClient.loadCollection({
        collection_name:'xxxx'
    })
```

2. Execute insert frequently, throw error
```typescript
milvusClient.insert({ collection_name: 'xxxx', data: [{ id: 'xxxx', vector: [xxx,xxx....]}] })
```

**Milvus-node-sdk version:**
v2.2.24

**Milvus version:**
v2.4.5

**Comment by 759325100** [comment]
Hope to get the answer

**Comment by shanghaikid** [comment]
frequently, how frequently?

**Comment by 759325100** [comment]
> frequently, how frequently?

update sdk version to latest
problem is resolved
thx

**Comment by shanghaikid** [comment]
Just one note, please use `loadCollectionSync` to load your collection.
