### ISSUE TITLE
three questions....

### ISSUE THREAD

**Issue by coollofty** [milvus-io/milvus-sdk-node#70]
1. How to capture when new MilvusClient(addr) fails?
2. The document lists some functions that have async, some are not, but basically all the return values of the functions in the API manual are promises, how to understand ?
3. Currently, I call all async functions (such createCollection/hasCollection/insert etc.), they will be blocked. That is, neither the then nor the catch responds. No matter how long you wait, what could be the reason? 

Thanks ^_^

**Comment by nameczz** [comment]
1. Use try catch to catch error
2. Async or sync is depend on Milvus. For example: if flushSync return response, means Milvus flush done. If flush return response, just means Milvus start flush, may need some time to flush data.
3. What's your Milvus and node-sdk version ? May be you can check your Milvus docker is active or not. Or restart your Milvus try again.

Also you can try [milvus-insight](https://github.com/zilliztech/milvus-insight) to manage Milvus. It's also depend on node-sdk.
